name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ansible-syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core

      - name: Validate playbook syntax
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          checked=0
          for playbook in playbooks/*.yml playbooks/*.yaml; do
            [ -f "$playbook" ] || continue
            checked=1
            if [ -s "$playbook" ]; then
              echo "Checking $playbook"
              ansible-playbook --syntax-check -i localhost, "$playbook"
            else
              echo "Skipping empty playbook $playbook"
            fi
          done
          if [ "$checked" -eq 0 ]; then
            echo "No playbooks found to validate."
          fi

      - name: Test runner script
        shell: bash
        env:
          ANSIBLE_VAULT_PASSWORD_FILE: /tmp/ci-vault-pass
        run: |
          set -euo pipefail
          printf 'ci-test-password\n' > "$ANSIBLE_VAULT_PASSWORD_FILE"
          ./runner.sh help > /tmp/runner-help.txt
          grep -q "Usage:" /tmp/runner-help.txt
          ./runner.sh list > /tmp/runner-list.txt
          grep -q "Verfügbare Playbooks" /tmp/runner-list.txt
          ./runner.sh run site --syntax-check
